return {
  version = "1.9",
  luaversion = "5.1",
  tiledversion = "1.9.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 20,
  height = 20,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 3,
  nextobjectid = 83,
  properties = {},
  tilesets = {
    {
      name = "tiles",
      firstgid = 1,
      class = "",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 20,
      image = "tiles.png",
      imagewidth = 320,
      imageheight = 1264,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      wangsets = {},
      tilecount = 1580,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 20,
      height = 20,
      id = 1,
      name = "Tile Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "Object Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "player",
          class = "",
          shape = "rectangle",
          x = 144,
          y = 288,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 1103,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "enemy",
          class = "",
          shape = "rectangle",
          x = 144,
          y = 240,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 283,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 16,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 32,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 48,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 64,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 80,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 96,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 112,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 128,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 128,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 144,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 160,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 176,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 192,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 208,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 224,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 240,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 256,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 272,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 288,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 16,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 32,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 48,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 64,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 80,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 96,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 112,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 128,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 128,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 144,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 160,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 176,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 192,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 208,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 224,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 240,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 256,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 272,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 288,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 32,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 48,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 64,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 80,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 112,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 144,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 160,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 176,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 192,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 224,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 240,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 256,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 272,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 288,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 304,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 32,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 48,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 64,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 80,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 112,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 144,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 160,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 72,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 176,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 73,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 192,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 74,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 75,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 224,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 76,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 240,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 77,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 256,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 78,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 272,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 79,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 288,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 80,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 304,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 81,
          name = "stair_up",
          class = "",
          shape = "rectangle",
          x = 144,
          y = 304,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 534,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
