return {
  version = "1.9",
  luaversion = "5.1",
  tiledversion = "1.9.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 20,
  height = 20,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 3,
  nextobjectid = 240,
  properties = {},
  tilesets = {
    {
      name = "tiles",
      firstgid = 1,
      class = "",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 20,
      image = "tiles.png",
      imagewidth = 320,
      imageheight = 1264,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      wangsets = {},
      tilecount = 1580,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 20,
      height = 20,
      id = 1,
      name = "Tile Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "Object Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 20,
          name = "player",
          class = "",
          shape = "rectangle",
          x = 96,
          y = 288,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 1103,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "enemy",
          class = "",
          shape = "rectangle",
          x = 96,
          y = 256,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 283,
          visible = true,
          properties = {}
        },
        {
          id = 139,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 140,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 16,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 141,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 32,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 142,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 48,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 143,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 64,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 144,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 80,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 145,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 96,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 146,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 112,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 147,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 128,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 148,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 128,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 149,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 144,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 150,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 160,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 151,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 176,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 152,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 192,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 153,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 208,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 154,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 224,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 155,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 240,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 157,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 256,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 158,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 272,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 159,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 288,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 160,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 16,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 161,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 162,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 16,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 163,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 32,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 164,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 48,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 165,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 64,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 166,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 80,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 167,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 96,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 168,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 112,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 169,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 128,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 170,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 128,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 171,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 144,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 172,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 160,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 173,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 176,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 174,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 192,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 175,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 208,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 176,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 224,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 177,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 240,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 178,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 256,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 179,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 272,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 180,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 288,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 181,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 201,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 32,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 202,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 48,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 203,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 64,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 204,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 80,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 205,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 206,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 112,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 207,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 208,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 144,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 209,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 160,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 210,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 176,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 211,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 192,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 212,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 213,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 224,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 214,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 240,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 215,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 256,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 216,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 272,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 217,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 288,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 218,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 304,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 219,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 32,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 220,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 48,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 221,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 64,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 222,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 80,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 223,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 224,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 112,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 225,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 226,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 144,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 227,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 160,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 228,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 176,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 229,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 192,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 230,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 231,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 224,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 232,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 240,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 233,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 256,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 234,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 272,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 235,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 288,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 236,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 304,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 523,
          visible = true,
          properties = {}
        },
        {
          id = 237,
          name = "stair_up",
          class = "",
          shape = "rectangle",
          x = 96,
          y = 304,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 534,
          visible = true,
          properties = {}
        },
        {
          id = 239,
          name = "stair_down",
          class = "",
          shape = "rectangle",
          x = 208,
          y = 304,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 533,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
